Work around some glitches in the unicode handling of test_usno
This is needed to get rid of errors like
```
ERROR: test_usno (ephem.tests.test_usno.T11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyephem-3.7.6.0/.pybuild/pythonX.Y_3.5/build/ephem/tests/test_usno.py", line 460, in test_usno
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 356: ordinal not in range(128)
```
when testing under Python-3.5